
import unittest
from scripts.wntransformer import *
import os
from collections import defaultdict
from unittest import TestCase

class TransformerTestCase(unittest.TestCase):

    def test_transformer(self):
    test1 = 'evaluation dye exclusion colony inhibition technique detection polyoma specific cell mediate immunity cellular immunity direct polyoma virus induced antigen observe c3h hej splenic lymphoid cell ncbitaxon10090 sensitize short term immunization schedule syngeneic polyoma 4198 4198v meshd009369 cell polyoma specificity response show demonstration splenic cell dba 2j animal meshd014412 cytotoxic c3h 4198 4198v cell cell another cell line c3h origin polyoma specific response syngeneic system detectable dye exclusion assay colony inhibition procedure colony inhibition cell observe sensitize lymphoid cell allogeneic syngeneic system'
    test2 = 'potentiation ncbitaxon10515 associate virus ncbitaxon10310 transform cell ncbitaxon10310 ncbitaxon10310 transform cell line 333 8 9 inoculate adeno virus associate virus type 3 aav 3 examine immunofluorescent fa technique evidence aav 3 antigen synthesis antiserum prepared three meshd012967 dissociate structural polypeptide vp 1 vp 2 vp 3 aav 3 whole aav 3 virion use probe search aav 3 fa stainable antigen synthesize cell 333 8 9 cell inoculate aav 3 alone produced fa stainable antigen detect vp 1 vp 3 whole virion antiserum vp 2 antiserum coinfection aav 3 inoculated 333 8 9 cells with either ncbitaxon10515 ncbitaxon10515 ncbitaxon10298 ncbitaxon10298 helper permit formation fa stainable antigen detect antiserum include vp 2 antiserum contrast 333 8 9 cell bhk 21 cell fail produce aav 3 fa stainable antigen inoculate aav 3 alone addition either ncbitaxon10515 ncbitaxon10298 helper lead formation antigen detect vp whole virion antiserum result suggest 333 8 9 cell enhance formation two three aav 3 structural polypeptide incomplete potentiation related ncbitaxon10310 genetic material possess cell'
    expected1 = 'evaluation dye exclusion colony inhibition technique detection polyoma specific cell mediate immunity cellular immunity direct polyoma virus induced antigen detect c3h hej splenic lymphoid cell ncbitaxon10090 sensitize short term immunization schedule syngeneic polyoma 4198 4198v meshd009369 cell polyoma specificity response show demonstration splenic cell dba 2j animal meshd014412 cytotoxic c3h 4198 4198v cell cell another cell line c3h line polyoma specific response syngeneic system detectable dye exclusion assay colony inhibition procedure colony inhibition cell detect sensitize lymphoid cell allogeneic syngeneic system'
    expected2 = 'potentiation ncbitaxon10515 associate virus ncbitaxon10310 transform cell ncbitaxon10310 ncbitaxon10310 transform cell line 333 8 9 inoculate adeno virus associate virus type 3 aav 3 examine immunofluorescent fa technique evidence aav 3 antigen synthesis antiserum prepared 3 meshd012967 dissociate structural polypeptide vp 1 vp 2 vp 3 aav 3 whole aav 3 virion use probe search aav 3 fa stainable antigen synthesize cell 333 8 9 cell inoculate aav 3 alone produced fa stainable antigen detect vp 1 vp 3 whole virion antiserum vp 2 antiserum coinfection aav 3 inoculate 333 8 9 cell with either ncbitaxon10515 ncbitaxon10515 ncbitaxon10298 ncbitaxon10298 helper permit formation fa stainable antigen detect antiserum include vp 2 antiserum line 333 8 9 cell bhk 21 cell fail produce aav 3 fa stainable antigen inoculate aav 3 alone addition either ncbitaxon10515 ncbitaxon10298 helper lead formation antigen detect vp whole virion antiserum result suggest 333 8 9 cell enhance formation 2 3 aav 3 structural polypeptide incomplete potentiation associate ncbitaxon10310 genetic material possess cell'
