
import unittest
from scripts.transform import*
import os
#import pytest
from unittest import TestCase
from collections import defaultdict


class TransformerTestCase(unittest.TestCase):

    def test_transformer(self):
        dict = {'cell': 'cell', '3': '3', 'aav': 'aav', 'vp': 'vp', 'antigen': 'antigen', 'antiserum': 'antiserum', 'polyoma': 'polyoma', '333': '333', '8': '8', '9': '9', 'fa': 'fa', 'virus': 'virus', 'ncbitaxon10515': 'ncbitaxon10515', 'ncbitaxon10310': 'ncbitaxon10310', 'stainable': 'stainable', 'colony': 'colony', 'inhibition': 'inhibition', 'c3h': 'c3h', 'syngeneic': 'syngeneic', 'inoculate': 'inoculate', '2': '2', 'whole': 'whole', 'virion': 'virion', 'detect': 'detect', 'ncbitaxon10298': 'ncbitaxon10298', 'formation': 'formation', 'dye': 'dye', 'exclusion': 'exclusion', 'technique': 'technique', 'specific': 'specific', 'immunity': 'immunity', 'observe': 'detect', 'splenic': 'splenic', 'lymphoid': 'lymphoid', 'sensitize': 'sensitize', '4198': '4198', '4198v': '4198v', 'response': 'response', 'line': 'line', 'system': 'system', 'potentiation': 'potentiation', 'associate': 'associate', 'transform': 'transform', 'three': '3', 'structural': 'structural', 'polypeptide': 'polypeptide', '1': '1', 'alone': 'alone', 'either': 'either', 'helper': 'helper', 'evaluation': 'evaluation', 'detection': 'detection', 'mediate': 'mediate', 'cellular': 'cellular', 'direct': 'direct', 'induced': 'induced', 'hej': 'hej', 'ncbitaxon10090': 'ncbitaxon10090', 'short': 'short', 'term': 'term', 'immunization': 'immunization', 'schedule': 'schedule', 'meshd009369': 'meshd009369', 'specificity': 'specificity', 'show': 'show', 'demonstration': 'demonstration', 'dba': 'dba', '2j': '2j', 'animal': 'animal', 'meshd014412': 'meshd014412', 'cytotoxic': 'cytotoxic', 'another': 'another', 'origin': 'line', 'detectable': 'detectable', 'assay': 'assay', 'procedure': 'procedure', 'allogeneic': 'allogeneic', 'adeno': 'adeno', 'type': 'type', 'examine': 'examine', 'immunofluorescent': 'immunofluorescent', 'evidence': 'evidence', 'synthesis': 'synthesis', 'prepared': 'prepared', 'meshd012967': 'meshd012967', 'dissociate': 'dissociate', 'use': 'use', 'probe': 'probe', 'search': 'search', 'synthesize': 'synthesize', 'produced': 'produced', 'coinfection': 'coinfection', 'inoculated': 'inoculate', 'cells': 'cell', 'with': 'with', 'permit': 'permit', 'include': 'include', 'contrast': 'line', 'bhk': 'bhk', '21': '21', 'fail': 'fail', 'produce': 'produce', 'addition': 'addition', 'lead': 'lead', 'result': 'result', 'suggest': 'suggest', 'enhance': 'enhance', 'two': '2', 'incomplete': 'incomplete', 'related': 'associate', 'genetic': 'genetic', 'material': 'material', 'possess': 'possess'}
        test1 = '163318	1975	evaluation dye exclusion colony inhibition technique detection polyoma specific cell mediate immunity cellular immunity direct polyoma virus induced antigen observe c3h hej splenic lymphoid cell ncbitaxon10090 sensitize short term immunization schedule syngeneic polyoma 4198 4198v meshd009369 cell polyoma specificity response show demonstration splenic cell dba 2j animal meshd014412 cytotoxic c3h 4198 4198v cell cell another cell line c3h origin polyoma specific response syngeneic system detectable dye exclusion assay colony inhibition procedure colony inhibition cell observe sensitize lymphoid cell allogeneic syngeneic system
        test2 = '163319	1975	potentiation ncbitaxon10515 associate virus ncbitaxon10310 transform cell ncbitaxon10310 ncbitaxon10310 transform cell line 333 8 9 inoculate adeno virus associate virus type 3 aav 3 examine immunofluorescent fa technique evidence aav 3 antigen synthesis antiserum prepared three meshd012967 dissociate structural polypeptide vp 1 vp 2 vp 3 aav 3 whole aav 3 virion use probe search aav 3 fa stainable antigen synthesize cell 333 8 9 cell inoculate aav 3 alone produced fa stainable antigen detect vp 1 vp 3 whole virion antiserum vp 2 antiserum coinfection aav 3 inoculated 333 8 9 cells with either ncbitaxon10515 ncbitaxon10515 ncbitaxon10298 ncbitaxon10298 helper permit formation fa stainable antigen detect antiserum include vp 2 antiserum contrast 333 8 9 cell bhk 21 cell fail produce aav 3 fa stainable antigen inoculate aav 3 alone addition either ncbitaxon10515 ncbitaxon10298 helper lead formation antigen detect vp whole virion antiserum result suggest 333 8 9 cell enhance formation two three aav 3 structural polypeptide incomplete potentiation related ncbitaxon10310 genetic material possess cell'
        expected1 = '163318 1975     evaluation dye exclusion colony inhibition technique detection polyoma specific cell mediate immunity cellular immunity direct polyoma virus induced antigen detect c3h hej splenic lymphoid cell ncbitaxon10090 sensitize short term immunization schedule syngeneic polyoma 4198 4198v meshd009369 cell polyoma specificity response show demonstration splenic cell dba 2j animal meshd014412 cytotoxic c3h 4198 4198v cell cell another cell line c3h line polyoma specific response syngeneic system detectable dye exclusion assay colony inhibition procedure colony inhibition cell detect sensitize lymphoid cell allogeneic syngeneic system'
        expected2 = '163319 1975     potentiation ncbitaxon10515 associate virus ncbitaxon10310 transform cell ncbitaxon10310 ncbitaxon10310 transform cell line 333 8 9 inoculate adeno virus associate virus type 3 aav 3 examine immunofluorescent fa technique evidence aav 3 antigen synthesis antiserum prepared 3 meshd012967 dissociate structural polypeptide vp 1 vp 2 vp 3 aav 3 whole aav 3 virion use probe search aav 3 fa stainable antigen synthesize cell 333 8 9 cell inoculate aav 3 alone produced fa stainable antigen detect vp 1 vp 3 whole virion antiserum vp 2 antiserum coinfection aav 3 inoculate 333 8 9 cell with either ncbitaxon10515 ncbitaxon10515 ncbitaxon10298 ncbitaxon10298 helper permit formation fa stainable antigen detect antiserum include vp 2 antiserum line 333 8 9 cell bhk 21 cell fail produce aav 3 fa stainable antigen inoculate aav 3 alone addition either ncbitaxon10515 ncbitaxon10298 helper lead formation antigen detect vp whole virion antiserum result suggest 333 8 9 cell enhance formation 2 3 aav 3 structural polypeptide incomplete potentiation associate ncbitaxon10310 genetic material possess cell'
        result1 = Transformer.transform(test1, dict)
        self.assertEqual(expected1, result1, 'Incorrect Transformation')